# Generated by Django 2.2.10 on 2023-07-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.TextField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
